from . import materiais
from . import maquinas
from . import manutencoes
from . import movimentacoes
from . import pedidos
from . import auth
from . import usuarios_sistema
from . import colaboradores
from . import dashboard
from . import demandas
from . import configuracoes
from . import departamentos
from . import cargos
