# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('styles/style.qss', 'styles'),
        ('version.json', '.'),
        ('version.py', '.'),
    ],
    hiddenimports=[
        'pyexpat',
        'xml.etree.ElementTree',
        'xml.parsers.expat',
        'openpyxl',
        'reportlab',
        'PIL',
        'PIL._imaging',
        'PIL._imagingft',
        'PIL._imagingtk',
        'PIL._webp',
        'PIL.Image',
        'PIL.ImageFile',
        'PIL.ImagePalette',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageOps',
        'PIL.ImageChops',
        'PIL.ImageColor',
        'PIL.ImageFilter',
        'PIL.ImageMath',
        'PIL.ImageMode',
        'PIL.ImageShow',
        'PIL.ImageWin',
        'PIL.ImageQt',
        'PIL.ImageSequence',
        'PIL.ImageCms',
        'PIL.ImageMime',
        'PIL.ImageTransform',
        'PIL.ImageStat',
        'PIL.ImagePath',
        'requests',
        'dotenv',
        'psutil',
        'jose',
        'passlib',
        'apscheduler',
        'sqlalchemy',
        'psycopg2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ProjectParallel',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)